config/routes.rb
Rails.application.routes.draw do
  resources :store_room_exits do
    collection do
      get 'entry', to: 'store_room_exits#entry'
      post 'entry', to: 'store_room_exits#entry_point'
    end

    member do
      get 'input_weight'
      post 'input_weight', to: 'store_room_exits#update_input_weight'
    end
  end
  resources :receive_donation_requests
  resources :store_room_entries
  resources :donation_requests do
    collection do
      get 'entry', to: 'donation_requests#entry'
      post 'entry', to: 'donation_requests#entry_point'
    end
    member do
      get 'accepted_paper', to: 'donation_requests#accepted_paper'
      get 'thankyou', to: 'donation_requests#thankyou'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/store_room_entry.rb
class StoreRoomEntry < ApplicationRecord
  belongs_to :donation_request
  has_many :store_room_entry_contents, dependent: :destroy
  accepts_nested_attributes_for :store_room_entry_contents, allow_destroy: true
end

app/controllers/store_room_entries_controller.rb
class StoreRoomEntriesController < ApplicationController
  before_action :set_store_room_entry, only: %i[ show edit update destroy ]

  # GET /store_room_entries or /store_room_entries.json
  def index
    @store_room_entries = StoreRoomEntry.all
  end

  # GET /store_room_entries/1 or /store_room_entries/1.json
  def show
  end

  # GET /store_room_entries/new
  def new
    from_id = params[:donation_request_id]
    from_dr = DonationRequest.find(from_id)
    @store_room_entry = StoreRoomEntry.new
    @store_room_entry.donation_request_id = from_dr.id
    from_dr.donation_request_contents.each do |dr_content|
      dr_content.count.times do |i|
        y = dr_content.created_at.year % 1_000
        m = dr_content.created_at.month.to_s(16)
        d = dr_content.created_at.day
        @store_room_entry.store_room_entry_contents.build(
          maker: dr_content.maker,
          name: "#{dr_content.name}-#{i}",
          barcode: format("A#{y}#{m}#{d}%05<number>dA", number: i),
          donation_request_content_id: dr_content.id
        )
      end
    end
  end

  # GET /store_room_entries/1/edit
  def edit
  end

  # POST /store_room_entries or /store_room_entries.json
  def create
    @store_room_entry = StoreRoomEntry.new(store_room_entry_params)

    respond_to do |format|
      if @store_room_entry.save
        format.html { redirect_to store_room_entry_url(@store_room_entry), notice: "Store room entry was successfully created." }
        format.json { render :show, status: :created, location: @store_room_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store_room_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_room_entries/1 or /store_room_entries/1.json
  def update
    respond_to do |format|
      if @store_room_entry.update(store_room_entry_params)
        format.html { redirect_to store_room_entry_url(@store_room_entry), notice: "Store room entry was successfully updated." }
        format.json { render :show, status: :ok, location: @store_room_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store_room_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_room_entries/1 or /store_room_entries/1.json
  def destroy
    @store_room_entry.destroy

    respond_to do |format|
      format.html { redirect_to store_room_entries_url, notice: "Store room entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_room_entry
      @store_room_entry = StoreRoomEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_room_entry_params
      params.require(:store_room_entry).permit(:donation_request_id)
    end
end

app/helpers/store_room_entries_helper.rb
module StoreRoomEntriesHelper
end

app/views/store_room_entries/_form.html.erb
<%= form_with(model: store_room_entry) do |form| %>
  <% if store_room_entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store_room_entry.errors.count, "error") %> prohibited this store_room_entry from being saved:</h2>

      <ul>
        <% store_room_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :donation_request_id %>

  <%= link_to '元寄附申請の表示', edit_donation_request_path(store_room_entry.donation_request.id) %>

  <% store_room_entry.store_room_entry_contents.each do |content| %>
    <%= form.fields_for :store_room_entry_contents, content do |content_f| %>
      <%= content_f.hidden_field :id %>
      <div class="row">
        <div class="col-md-8 pb-4 border-bottom">
          <%= content_f.label :name, 'ラベル名', class: 'form-label' %>
          <%= content_f.text_field :name, class: 'form-control' %>
          <span class="text-muted">
          </span>
        </div>
        <div class="col-md-4 pb-4 border-bottom">
          <%= content_f.label :barcode, 'バーコード', class: 'form-label' %>
          <%= content_f.text_field :barcode, class: 'form-control', readonly: true %>
          <span class="text-muted">
            賞味期限 <%= l(content.donation_request_content.expiry_date) %>
          </span>
        </div>
      </div>
    <% end %>
  <% end %>


  <div>
    <%= form.submit 'エクセルのダウンロード', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/store_room_entries/_store_room_entry.html.erb
<div id="<%= dom_id store_room_entry %>">
  <p>
    <strong>Donation request:</strong>
    <%= store_room_entry.donation_request_id %>
  </p>

</div>

app/views/store_room_entries/edit.html.erb
<h1>Editing store room entry</h1>

<%= render "form", store_room_entry: @store_room_entry %>

<br>

<div>
  <%= link_to "Show this store room entry", @store_room_entry %> |
  <%= link_to "Back to store room entries", store_room_entries_path %>
</div>

app/views/store_room_entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Store room entries</h1>

<div id="store_room_entries">
  <% @store_room_entries.each do |store_room_entry| %>
    <%= render store_room_entry %>
    <p>
      <%= link_to "Show this store room entry", store_room_entry %>
    </p>
  <% end %>
</div>

<%= link_to "New store room entry", new_store_room_entry_path %>

app/views/store_room_entries/new.html.erb
<%= standard_container do %>
  <%= render 'shared/paper_title', title: '入庫表(バーコード)' %>

  <%= render "form", store_room_entry: @store_room_entry %>
<% end %>

app/views/store_room_entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store_room_entry %>