config/routes.rb
Rails.application.routes.draw do
  resources :store_room_exits do
    collection do
      get 'entry', to: 'store_room_exits#entry'
      post 'entry', to: 'store_room_exits#entry_point'
    end

    member do
      get 'input_weight'
      post 'input_weight', to: 'store_room_exits#update_input_weight'
    end
  end
  resources :receive_donation_requests
  resources :store_room_entries
  resources :donation_requests do
    collection do
      get 'entry', to: 'donation_requests#entry'
      post 'entry', to: 'donation_requests#entry_point'
    end
    member do
      get 'accepted_paper', to: 'donation_requests#accepted_paper'
      get 'thankyou', to: 'donation_requests#thankyou'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/store_room_exit.rb
class StoreRoomExit < ApplicationRecord
  has_many :store_room_exit_contents
end

app/controllers/store_room_exits_controller.rb
class StoreRoomExitsController < ApplicationController
  before_action :set_store_room_exit, only: %i[ show edit update destroy input_weight update_input_weight]

  # GET /store_room_exits or /store_room_exits.json
  def index
    @store_room_exits = StoreRoomExit.all
  end

  # GET /store_room_exits/1 or /store_room_exits/1.json
  def show
  end

  # GET /store_room_exits/new
  def new
    @store_room_exit = StoreRoomExit.new
  end

  # GET /store_room_exits/1/edit
  def edit
  end

  def input_weight
    @form = FormInputWeight.new
    @store_room_exit.store_room_exit_contents.where(is_drive: true).order(:code).uniq(&:code).each_with_index do |c, i|
      @form.send("name#{i+1}=", c.name)
      @form.send("weight#{i+1}=", 0)
    end
  end

  def update_input_weight
    f = FormInputWeight.new(input_weight_params)

    respond_to do |format|
      format.html {
        redirect_to store_room_exit_url(@store_room_exit),
                    notice: "出庫しました"
      }
    end
  end

  # POST /store_room_exits or /store_room_exits.json
  def create
    @store_room_exit                                  = StoreRoomExit.new(store_room_exit_params)
    from                                              = @store_room_exit.from_receive_donation_request_id
    @store_room_exit.from_receive_donation_request_id = ReceiveDonationRequest.last&.id
    respond_to do |format|
      if @store_room_exit.save
        format.html {
          redirect_to edit_store_room_exit_url(@store_room_exit, from: from),
                      notice: "出庫申請を開始します"
        }
        format.json { render :show, status: :created, location: @store_room_exit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store_room_exit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_room_exits/1 or /store_room_exits/1.json
  def update
    respond_to do |format|
      if params[:commit] == 'この内容で出庫'
        if @store_room_exit.store_room_exit_contents.map(&:is_drive).include?(true)
          @store_room_exit.save!
          format.html {
            redirect_to input_weight_store_room_exit_path(@store_room_exit)
          }
        else
          @store_room_exit.draft = false
          @store_room_exit.save!
          format.html {
            redirect_to store_room_exit_url(@store_room_exit),
                        notice: "出庫しました"
          }
        end

      else
        c    = @store_room_exit.store_room_exit_contents.count
        code = params[:form_append_item][:code]
        lc = @store_room_exit.store_room_exit_contents.where(code:).count

        if code.to_s.start_with?('999')
          code_map = {
            '99900001': '菓子類',
            '99900002': '缶詰・瓶詰類',
            '99900003': '米・餅・粉・麺類',
            '99900004': '調味料類',
            '99900005': 'インスタント・レトルト類',
            '99900006': '飲料・嗜好品類',
            '99900007': '乾物類',
            '99900008': '乳児食・介護食・栄養補助食類',
            '99900009': 'その他',
          }
          t = code_map[code.to_s.to_sym] || '不明'
          created = @store_room_exit.store_room_exit_contents.create(
            code:,
            name: "#{t} (ドライブ)-#{lc + 1}",
            content_type: 1,
            is_drive: true
          )
          format.html {
            redirect_to edit_store_room_exit_url(@store_room_exit),
                        notice: "#{created.name}を追加しました"
          }
          format.json { render :show, status: :ok, location: @store_room_exit }

        else
          entry = StoreRoomEntryContent.find_by(barcode: code)
          if entry
            if lc.zero?
              created = @store_room_exit.store_room_exit_contents.create(
                code:,
                name:         entry.name,
                content_type: entry.content_type,
                weight:       entry.weight
              )
              format.html {
                redirect_to edit_store_room_exit_url(@store_room_exit),
                            notice: "#{created.name}を追加しました"
              }
            else
              format.html {
                redirect_to edit_store_room_exit_url(@store_room_exit),
                            notice: "#{code}は重複しています。"
              }
            end
          else
            format.html {
              redirect_to edit_store_room_exit_url(@store_room_exit),
                          notice: "#{code} はみつかりませんでした。"
            }
          end
        end
      end
    end
  end

  # DELETE /store_room_exits/1 or /store_room_exits/1.json
  def destroy
    @store_room_exit.destroy

    respond_to do |format|
      format.html { redirect_to store_room_exits_url, notice: "Store room exit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store_room_exit
    @store_room_exit = StoreRoomExit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def store_room_exit_params
    params.require(:store_room_exit).permit(:from_receive_donation_request_id)
  end

  def input_weight_params
    params.require(:form_input_weight).permit(
      :name1, :weight1, :name2, :weight2,
      :name3, :weight3, :name4, :weight4,
      :name5, :weight5, :name6, :weight6,
      :name7, :weight7, :name8, :weight8,
      :name9, :weight9
    )
  end
end

app/helpers/store_room_exits_helper.rb
module StoreRoomExitsHelper
end

app/views/store_room_exits/_form.html.erb
<%= form_with(model: store_room_exit) do |form| %>
  <% if store_room_exit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store_room_exit.errors.count, "error") %> prohibited this store_room_exit from being saved:</h2>

      <ul>
        <% store_room_exit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if store_room_exit.persisted? %>
    <% entry = ReceiveDonationRequest.find(store_room_exit.from_receive_donation_request_id) %>
    <div class="row">
      <div class="col">
        <span class="text-muted">出庫日</span><br>
        <strong>
          <%= l(Time.current, format: :long) %>
        </strong>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <span class="text-muted">団体名</span><br>
        <strong>
          <%= entry.name %>
        </strong>
      </div>
      <div class="col">
        <span class="text-muted">訪問者氏名</span><br>
        <strong>
          <%= entry.name %>
        </strong>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <span class="text-muted">使用目的</span><br>
        <strong>
          <%= entry.reason %>
        </strong>
      </div>
    </div>
    <hr>
  <% else %>
    <div class="row m-3">
      <div class="col">
        <%= form.label :name, '出庫受付カードをスキャンしてください', class: 'form-label display-6' %>
        <%= form.text_field :from_receive_donation_request_id, class: 'form-control', autofocus: true, autocomplete: 'off' %>
      </div>
    </div>

    <div class="d-grid gap-2 mt-1">
      <%= form.submit '出庫開始', class: 'btn btn-primary' %>
    </div>

  <% end %>
<% end %>

<% if store_room_exit.persisted? %>
  <%= form_with(model: FormAppendItem.new, url: store_room_exit_path(store_room_exit), method: :PATCH) do |form| %>
    <div class="row">
      <div class="col">
        <% if store_room_exit.store_room_exit_contents.count >= 50 %>
          <%= form.text_field :code, class: 'form-control', placeholder: '50を超えているので追加できません', disabled: true %>
        <% else %>
          <%= form.text_field :code, class: 'form-control', autofocus: true, placeholder: 'ここでバーコードをスキャンしてください' %>
        <% end %>
      </div>
    </div>
    <div class="row m-1">
      <div class="col">
        現在: <%= store_room_exit.store_room_exit_contents.count %> 個 / 50個
      </div>
    </div>
    <div class="d-grid gap-2 mt-1">
      <%= form.submit 'バーコードで追加', class: 'btn btn-primary' %>
    </div>


  <table class="table border-1 table-striped">
    <thead>
    <tr>
      <td>
        バーコード
      </td>
      <td>
        種別
      </td>
      <td>
        食品名
      </td>
      <td>
        重さ(kg)
      </td>
      <td>
        取消
      </td>
    </tr>
    </thead>
    <tbody>
    <% store_room_exit.store_room_exit_contents.order(id: :desc).each do |content| %>
      <tr>
        <td class="font-monospace">
          <% if content.is_drive %>
            <small><%= content.name %></small><br/>
            <small>(なし)</small>
          <% else %>
            <%= content.code %>
          <% end %>
        </td>
        <td><%= content.content_type %></td>
        <td><%= content.name %></td>
        <% if content.is_drive %>
          <td class="text-end">
            -
          </td>
        <% else %>
          <td class="text-end">
            <%= (content.weight.to_i/ 1_000.0).round(2).to_fs(:rounded, precision: 2) %>
          </td>
        <% end %>
        <td>
          <button class="btn btn-danger">x</button>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
    <%= form.submit 'この内容で出庫', class: 'btn btn-primary' %>
  <% end %>

<% end %>

app/views/store_room_exits/_store_room_exit.html.erb
<% entry = ReceiveDonationRequest.find_by(id: store_room_exit.from_receive_donation_request_id) %>
<% if entry %>
<div class="row">
  <div class="col">
    <span class="text-muted">出庫日</span><br>
    <span class="">
          <%= l(Time.current, format: :long) %>
          </span>
  </div>
</div>
<div class="row">
  <div class="col">
    <span class="text-muted">団体名</span><br>
    <span class="">
          <%= entry.name %>
          </span>
  </div>
  <div class="col">
    <span class="text-muted">出庫担当者氏名</span><br>
    <span class="">
          <%= entry.name %>
          </span>
  </div>
</div>
<div class="row">
  <div class="col">
    <span class="text-muted">使用目的</span><br>
    <span class="">
            <%= entry.reason %>
          </span>
  </div>
</div>
<hr>

<div class="row m-1">
  <div class="col">
    合計 <%= store_room_exit.store_room_exit_contents.count %> 個
  </div>
</div>

<hr>

<table class="table table-bordered border-1">
  <thead>
  <tr>
    <td>
      バーコード
    </td>
    <td>
      種別
    </td>
    <td>
      食品名
    </td>
    <td>
      重さ(kg)
    </td>
  </tr>
  </thead>
  <tbody>
  <% store_room_exit.store_room_exit_contents.order(id: :desc).each do |content| %>
    <tr>
      <td class="font-monospace">
        <% if content.is_drive %>
          <small><%= content.name %></small><br/>
          <small>(なし)</small>
        <% else %>
          <%= content.code %>
        <% end %>
      </td>
      <td><%= content.content_type %></td>
      <td><%= content.name %></td>
      <% if content.is_drive %>
        <td class="text-end">
          -
        </td>
      <% else %>
        <td class="text-end">
          <%= (content.weight.to_i / 1_000.0).to_fs(:rounded, precision: 2) %>
        </td>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>計</td>
    <td></td>
    <td></td>
    <td class="text-end">
      <%= (store_room_exit.store_room_exit_contents.sum(:weight)/1_000.0).to_fs(:rounded, precision: 2) %>
    </td>
  </tr>
  </tbody>
</table>
<% else %>
<% end %>

app/views/store_room_exits/edit.html.erb
<div class="container bg-light pb-5">
<%= render "form", store_room_exit: @store_room_exit %>
</div>

app/views/store_room_exits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>出庫表一覧</h1>

<div id="store_room_exits">
  <% @store_room_exits.order(id: :desc).each do |store_room_exit| %>
    <%= store_room_exit.created_at %>
    <p>
      <%= link_to "Show this store room exit", store_room_exit %>
    </p>
  <% end %>
</div>

<%= link_to "New store room exit", new_store_room_exit_path %>

app/views/store_room_exits/input_weight.html.erb
<%= standard_container do %>
  重さを入力してください。
  <%= form_with(method: :post, model: @form, url: input_weight_store_room_exit_path(@store_room_exit)) do |f| %>
    <div class="row">
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name1 %><br>
        <%= f.number_field :weight1, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name2 %><br>
        <%= f.number_field :weight2, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name3 %><br>
        <%= f.number_field :weight3, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name4 %><br>
        <%= f.number_field :weight4, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name5 %><br>
        <%= f.number_field :weight5, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name6 %><br>
        <%= f.number_field :weight6, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name7 %><br>
        <%= f.number_field :weight7, class: 'form-control' %>
      </div>
      <div class="col-md-6 pb-4 border-bottom">
        <%= @form.name8 %><br>
        <%= f.number_field :weight8, class: 'form-control' %>
      </div>
    </div>

    <%= f.submit '重さの入力', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/store_room_exits/new.html.erb
<%= standard_container do %>

  <%= render 'shared/paper_title', title: '食品出庫受付' %>
  <%= render "form", store_room_exit: @store_room_exit %>
<% end %>

app/views/store_room_exits/show.html.erb
<div class="container bg-light pb-5">
  <%= render @store_room_exit %>
</div>