config/routes.rb
Rails.application.routes.draw do
  resources :store_room_exits do
    collection do
      get 'entry', to: 'store_room_exits#entry'
      post 'entry', to: 'store_room_exits#entry_point'
    end

    member do
      get 'input_weight'
      post 'input_weight', to: 'store_room_exits#update_input_weight'
    end
  end
  resources :receive_donation_requests
  resources :store_room_entries
  resources :donation_requests do
    collection do
      get 'entry', to: 'donation_requests#entry'
      post 'entry', to: 'donation_requests#entry_point'
    end
    member do
      get 'accepted_paper', to: 'donation_requests#accepted_paper'
      get 'thankyou', to: 'donation_requests#thankyou'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/receive_donation_request.rb
class ReceiveDonationRequest < ApplicationRecord
end

app/controllers/receive_donation_requests_controller.rb
class ReceiveDonationRequestsController < ApplicationController
  before_action :set_receive_donation_request, only: %i[ show edit update destroy ]

  # GET /receive_donation_requests or /receive_donation_requests.json
  def index
    @receive_donation_requests = ReceiveDonationRequest.all
  end

  # GET /receive_donation_requests/1 or /receive_donation_requests/1.json
  def show
  end

  # GET /receive_donation_requests/new
  def new
    @receive_donation_request = ReceiveDonationRequest.new
  end

  # GET /receive_donation_requests/1/edit
  def edit
  end

  # POST /receive_donation_requests or /receive_donation_requests.json
  def create
    @receive_donation_request = ReceiveDonationRequest.new(receive_donation_request_params)

    respond_to do |format|
      if @receive_donation_request.save
        format.html { redirect_to receive_donation_request_url(@receive_donation_request), notice: "Receive donation request was successfully created." }
        format.json { render :show, status: :created, location: @receive_donation_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receive_donation_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receive_donation_requests/1 or /receive_donation_requests/1.json
  def update
    respond_to do |format|
      if @receive_donation_request.update(receive_donation_request_params)
        format.html { redirect_to receive_donation_request_url(@receive_donation_request), notice: "Receive donation request was successfully updated." }
        format.json { render :show, status: :ok, location: @receive_donation_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receive_donation_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receive_donation_requests/1 or /receive_donation_requests/1.json
  def destroy
    @receive_donation_request.destroy

    respond_to do |format|
      format.html { redirect_to receive_donation_requests_url, notice: "Receive donation request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receive_donation_request
      @receive_donation_request = ReceiveDonationRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def receive_donation_request_params
      params.require(:receive_donation_request).permit(
        :organization_name, :tel, :name, :scheduled_at, :fax, :used_at, :reason)
    end
end

app/helpers/receive_donation_requests_helper.rb
module ReceiveDonationRequestsHelper
end

app/views/receive_donation_requests/_form.html.erb
<%= form_with(model: receive_donation_request) do |form| %>
  <% if receive_donation_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(receive_donation_request.errors.count, "error") %> prohibited this receive_donation_request from being saved:</h2>

      <ul>
        <% receive_donation_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-md-6 pb-4 border-bottom">
      <%= form.label :organization_name, '貴団体名', class: 'form-label'%>
      <%= form.text_field :organization_name, required: true, class: 'form-control', placeholder: '団体名' %>
    </div>
    <div class="col-md-6 pb-4 border-bottom">
      <%= form.label :name, '当日ご担当者名(*)', class: 'form-label'%>
      <%= form.text_field :name, required: true, class: 'form-control', placeholder: '石川太郎' %>
    </div>
    <div class="col-md-6 pb-4 border-bottom">
      <%= form.label :tel, '当日連絡電話番号(*)', class: 'form-label'%>
      <%= form.telephone_field :tel, required: true, class: 'form-control', placeholder: '01234567890' %>
    </div>
    <div class="col-md-6 pb-4 border-bottom">
      <%= form.label :fax, 'FAX番号', class: 'form-label'%>
      <%= form.telephone_field :fax, class: 'form-control', placeholder: '01234567890' %>
    </div>
    <div class="col-md-6 pb-4 border-bottom">
      <%= form.label :scheduled_at, '出庫訪問予定日(*)', class: 'form-label'%>
      <%= form.datetime_field :scheduled_at, required: true, class: 'form-control' %>
      <span class="text-muted">出庫する予定日を指定してください。予定の変更をお願いする場合にはご連絡差し上げます。</span>
    </div>
    <div class="col-md-6 pb-4 border-bottom">
      <%= form.label :used_at, '使用予定日(*)', class: 'form-label'%>
      <%= form.date_field :used_at, required: true, class: 'form-control' %>
      <span class="text-muted">受け取った食品をいつ使う予定かご記入ください。</span>
    </div>
  </div>
  <div class="row">
    <div class="col-md pb-4 border-bottom">
      <%= form.label :reason, '利用目的(*)', class: 'form-label'%>
      <%= form.telephone_field :reason, class: 'form-control', placeholder: 'こども食堂で提供など' %>
    </div>
  </div>

  <div class="d-grid gap-2">
    <%= form.submit '申請します', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/receive_donation_requests/_receive_donation_request.html.erb
<div id="<%= dom_id receive_donation_request %>">
  <p>
    受付番号:
    <%= receive_donation_request.id %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= receive_donation_request.tel %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= receive_donation_request.name %>
  </p>

  <p>
    <strong>Scheduled time:</strong>
    <%= receive_donation_request.scheduled_time %>
  </p>

  <p>
    <strong>Accepted:</strong>
    <%= receive_donation_request.accepted %>
  </p>

</div>

app/views/receive_donation_requests/edit.html.erb
<h1>Editing receive donation request</h1>

<%= render "form", receive_donation_request: @receive_donation_request %>

<br>

<div>
  <%= link_to "Show this receive donation request", @receive_donation_request %> |
  <%= link_to "Back to receive donation requests", receive_donation_requests_path %>
</div>

app/views/receive_donation_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Receive donation requests</h1>

<div id="receive_donation_requests">
  <% @receive_donation_requests.each do |receive_donation_request| %>
    <%= render receive_donation_request %>
    <p>
      <%= link_to "Show this receive donation request", receive_donation_request %>
    </p>
  <% end %>
</div>

<%= link_to "New receive donation request", new_receive_donation_request_path %>

app/views/receive_donation_requests/new.html.erb
<%= standard_container do %>
  <%= render 'shared/paper_title', title: '食品出庫申請の作成' %>

  <%= render "form", receive_donation_request: @receive_donation_request %>
<% end %>

app/views/receive_donation_requests/show.html.erb
<%= standard_container do %>
  <h1><%= l(@receive_donation_request.scheduled_at, format: :long) %> で申請を受け付けました。</h1>
  <%# TODO 内容の再表示 %>
<% end %>