config/routes.rb
Rails.application.routes.draw do
  resources :store_room_exits do
    collection do
      get 'entry', to: 'store_room_exits#entry'
      post 'entry', to: 'store_room_exits#entry_point'
    end

    member do
      get 'input_weight'
      post 'input_weight', to: 'store_room_exits#update_input_weight'
    end
  end
  resources :receive_donation_requests
  resources :store_room_entries
  resources :donation_requests do
    collection do
      get 'entry', to: 'donation_requests#entry'
      post 'entry', to: 'donation_requests#entry_point'
    end
    member do
      get 'accepted_paper', to: 'donation_requests#accepted_paper'
      get 'thankyou', to: 'donation_requests#thankyou'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/donation_request.rb
class DonationRequest < ApplicationRecord
  has_many :donation_request_contents, dependent: :destroy
  has_one :store_room_entry, dependent: :destroy
  accepts_nested_attributes_for :donation_request_contents, allow_destroy: true
end

app/controllers/donation_requests_controller.rb
class DonationRequestsController < ApplicationController
  before_action :set_donation_request, only: %i[ show edit update destroy accepted_paper thankyou]

  # GET /donation_requests or /donation_requests.json
  def index
    @donation_requests = DonationRequest.all.order(created_at: :desc)
  end

  # GET /donation_requests/1 or /donation_requests/1.json
  def show
  end

  # GET /donation_requests/new
  def new
    @donation_request = DonationRequest.new
    if params[:email].present?
      email = params[:email]
      dr = DonationRequest.where(email: email).order(:created_at).last || @donation_requests
      @donation_request.email = email
      if dr.present?
        @donation_request.company = dr.company
        @donation_request.name = dr.name
        @donation_request.tel = dr.tel
        @donation_request.address = dr.address
      end
    end
  end

  # GET /donation_requests/1/edit
  def edit
  end

  def thankyou
  end

  # POST /donation_requests or /donation_requests.json
  def create
    @donation_request = DonationRequest.new(donation_request_params)

    respond_to do |format|
      if @donation_request.save
        format.html { redirect_to donation_request_url(@donation_request), notice: "Donation request was successfully created." }
        format.json { render :show, status: :created, location: @donation_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donation_requests/1 or /donation_requests/1.json
  def update
    respond_to do |format|
      if @donation_request.update(donation_request_params)
        format.html { redirect_to donation_request_url(@donation_request), notice: "Donation request was successfully updated." }
        format.json { render :show, status: :ok, location: @donation_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donation_requests/1 or /donation_requests/1.json
  def destroy
    @donation_request.destroy

    respond_to do |format|
      format.html { redirect_to donation_requests_url, notice: "Donation request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def entry
  end

  def accepted_paper

  end

  def entry_point
    email = params.dig(:form_entry, :email)
    if email.present?
      redirect_to new_donation_request_path(email:)
      return
    end
    redirect_to new_donation_request_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation_request
      @donation_request = DonationRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_request_params
      params.require(:donation_request).permit(:email, :company, :name, :address, :tel,
                                               donation_request_contents_attributes:
                                                 [:donation_request_id, :id, :maker, :expiry_date, :per_weight, :per_case, :count, :name, :content_type])
    end
end

app/helpers/donation_requests_helper.rb
module DonationRequestsHelper
end

app/views/donation_requests/_donation_request.html.erb
<div id="<%= dom_id donation_request %>">
  <p>
    <strong>Email:</strong>
    <%= donation_request.email %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= donation_request.company %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= donation_request.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= donation_request.address %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= donation_request.tel %>
  </p>

</div>

app/views/donation_requests/_form.html.erb
<%= form_with(model: donation_request) do |form| %>
  <% if donation_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donation_request.errors.count, "error") %> prohibited this donation_request from being saved:</h2>

      <ul>
        <% donation_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md pb-4 border-bottom">
      <%= form.label :email, 'メールアドレス', class: 'form-label' %>
      <%= form.text_field :email, class: 'form-control', required: true %>
    </div>
    <div class="col-md pb-4 border-bottom">
      <%= form.label :company, '寄附企業・団体名', class: 'form-label' %>
      <%= form.text_field :company, class: 'form-control', required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-md pb-4 border-bottom">
      <%= form.label :name, 'ご担当者名', class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>
    <div class="col-md pb-4 border-bottom">
      <%= form.label :tel, 'TEL', class: 'form-label' %>
      <%= form.telephone_field :tel, class: 'form-control', required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col pb-4">
      <%= form.label :address, '住所', class: 'form-label' %>
      <%= form.text_field :address, class: 'form-control', required: true %>
    </div>
  </div>

  <hr class="p-1">

  <% 3.times do |x| %>
    <%= form.fields_for :donation_request_contents, @donation_request.donation_request_contents[x] || @donation_request.donation_request_contents.build do |content_f| %>
      <%= content_f.hidden_field :id %>
      <h3><%= x+1 %>番目</h3>
      <div class="row">
        <div class="col-md-6 col-md pb-4 border-bottom">
          <%= content_f.label :name, '品名', class: 'form-label' %>
          <%= content_f.text_field :name, class: 'form-control' %>
        </div>
        <div class="col-md-6 col-md pb-4 border-bottom">
          <%= content_f.label :maker, 'メーカー', class: 'form-label' %>
          <%= content_f.text_field :maker, class: 'form-control' %>
        </div>
        <div class="col-md-4 col-md pb-4 border-bottom">
          <%= content_f.label :expiry_date, '賞味期限', class: 'form-label' %>
          <%= content_f.date_field :expiry_date, class: 'form-control' %>
          <span class="text-muted">月表記の場合は最終日を入力</span>
        </div>
        <div class="col-md-4 col-md pb-4 border-bottom">
          <%= content_f.label :per_weight, '1個あたり重量(g)', class: 'form-label' %>
          <%= content_f.number_field :per_weight, class: 'form-control' %>
        </div>

        <div class="col-md-4 col-md pb-4 border-bottom">
          <%= content_f.label :count, '個数', class: 'form-label' %>
          <%= content_f.number_field :count, class: 'form-control' %>
        </div>

        <!--
        <div class="col-md-2 pb-4 border-bottom">
          <%= content_f.label :content_type, '種類', class: 'form-label' %>
          <%= content_f.number_field :content_type, class: 'form-control' %>
          <span class="text-muted">省略可</span>
        </div>
        -->
      </div>
    <% end %>
  <% end %>

  <% unless edit %>
    <div class="row">
      <div class="col">
        <%= form.submit '寄附項目を追加', class: 'btn btn-secondary' %>
      </div>
      <div class="col">
        <%= form.submit '寄附項目をコピー追加', class: 'btn btn-secondary' %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= form.submit '申請する', class: 'btn btn-primary btn-block'%>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col">
        <%= form.submit '修正する', class: 'btn btn-primary btn-block'%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/donation_requests/accepted_paper.html.erb
<%= standard_container do %>
  <%= render 'shared/paper_title', title: '受領書' %>

  <%= render @donation_request %>

  <table class="table table-bordered">
    <thead><tr><td>品名</td><td>メーカー</td><td>重量/個</td><td>個数</td><td>重量(kg)</td></tr></thead>
    <tbody>
      <% @donation_request.donation_request_contents.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.maker %></td>
        <td><%= (c.per_weight / 1_000.0).round(2) %></td>
        <td><%= c.count %></td>
        <td><%= c.count * c.per_weight / 1000.0 %></td>
      </tr>
      <% end %>

    </tbody>
  </table>

  <div class="row border p-3 m-3">
    上記の寄贈食品を受領しました。<br>
    <%= l(Time.now, format: :long) %><br>
    いしかわフードバンク・ネット 理事長<br>
    〒920-0024  金沢市西念3丁目3-5 石川県勤労者福祉文化会館５F (さわやかU内)<br>
    TEL: 076-222-3310 FAX:076-222-3374
  </div>

<% end %>

app/views/donation_requests/edit.html.erb
<%= standard_container do %>
  <%= render 'shared/paper_title', title: '寄附申請 確認と修正' %>

  <%= render "form", donation_request: @donation_request, edit: true %>

  <hr class="p-1">

  <%= link_to '受領証を作成する', accepted_paper_donation_request_path(@donation_request), class: 'btn btn-primary' %>
  <%= link_to '入庫表(バーコード)を作成する', new_store_room_entry_path(donation_request_id: @donation_request.id) , class: 'btn btn-primary' %>

<% end %>

app/views/donation_requests/entry.html.erb
<% provide(:page_name, "") %>
<% provide(:no_header, true) %>

<%= standard_container do %>
  <%= render 'shared/paper_title', title: '寄附申請' %>

  <div class="row">
    <div class="col-lg-6 col-md-8 mx-auto text-center">
      <h2>寄附申請フォーム</h2>
    </div>
  </div>

  <%= form_with model: FormEntry.new, url: '' do |form| %>
    <%= form.email_field :email, class: 'form-control', placeholder: '空欄 or 以前申請したメールアドレス' %>
    <div class="text-muted col mx-auto text-center">
      以前に用いたメールアドレスを入力して先に進むことで、入力を省略できます。<br>
      はじめて申請する方は空欄のまま申請を進んでください。
    </div>
    <div class="row justify-content-center mx-2">
      <%= form.submit '申請へ進む', class: 'btn btn-primary mt-1' %>
    </div>
  <% end %>
<% end %>

app/views/donation_requests/index.html.erb
<%= standard_container do %>
  <%= render 'shared/paper_title', title: '寄附申請一覧' %>
    <div id="donation_requests">
      <table class="table table-bordered table-striped">
        <thead>
        <tr><th>申込日</th><th>企業・団体名</th><th>担当者</th><th>TEL</th><th>品数/重</th></tr>
        </thead>
        <tbody>
          <% @donation_requests.each do |donation_request| %>
            <tr>
              <td><%= link_to l(donation_request.created_at,format: :short), edit_donation_request_path(donation_request) %></td>
              <td><%= donation_request.company %></td>
              <td><%= donation_request.name %></td>
              <td><%= donation_request.tel %></td>
              <td><%= donation_request.donation_request_contents.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<% end %>

app/views/donation_requests/new.html.erb
<%= standard_container do %>
  <%= render 'shared/paper_title', title: '寄附申請' %>

  <%= render "form", donation_request: @donation_request, edit: false %>

<% end %>

app/views/donation_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @donation_request %>

<div>
  <%= link_to "Edit this donation request", edit_donation_request_path(@donation_request) %> |
  <%= link_to "Back to donation requests", donation_requests_path %>

  <%= button_to "Destroy this donation request", @donation_request, method: :delete %>
</div>

app/views/donation_requests/thankyou.html.erb
<% provide(:page_name, "") %>
<% provide(:no_header, true) %>

<%= standard_container do %>
  <%= render 'shared/paper_title', title: '寄附申請ありがとうございました' %>

  <div class="row">
    <div class="col-lg-12 col-md-12 mx-auto text-center">
      <h2><%= l(@donation_request.created_at, format: :long) %> に以下の内容で寄附申請を受け付けました。</h2>
         内容を確認し、ご連絡差し上げます。
    </div>
  </div>
<% end %>